---
type: //bool
---
type: //num
---
type: //int
---
type: //float
---
type: //date
---
type: //datetime
---
type: //str
---
type: //map
contents:
  foo: { type: //int, required: 1 }
  bar: { type: //int, required: 0 }
  baz:
    type: //map/uniform
    contents: { type: //int }
---
type: //array
size: { min: 1, max: 10 }
contents: { type: //array, contents: { type: //str } }
---
# [ $int, $str, ( { foo => $int } )? ]
type: //seq
contents:
  - type: //int
  - type: //str
tail:
  type: //array
  size: { min: 0, max: 1 }
  contents:
    type: //map
    contents:
      foo: { type: //int }
---
# [ $int, $str; $str, $int, $str ]
type: //seq
contents:
  - type: //int
  - type: //str
tail:
  type: //seq/cumulative
  contents:
    - type: //str
    - type: //int
    - type: //str
---
type: //seq
contents:
  - type: //codesimply.com/hostport
  - type: //codesimply.com/hostport
tail:
  type: //array
  size: { min: 1, max: 100 }
  contents: { type: //str }
---
type: //map
contents:
  account_id: { type: /pobox.com/account }
  sender:     { type: /pobox.com/email/env_addr }
  recipients:  
    type: //array
    contents: 
      type: /pobox.com/email/env_addr
      size: { min: 1 }
