---
type: //bool
---
type: //num
---
type: //int
---
type: //float
---
type: //date
---
type: //datetime
---
type: //str
---
type: //rec
contents:
  foo: { type: //int }
  bar: { type: //int, optional: 1 }
  baz:
    type: //rec/uniform
    optional: 0
    contents: { type: //int }
---
type: //arr
size: { min: 1, max: 10 }
contents: { type: //arr, contents: { type: //str } }
---
# [ $int, $str, ( { foo => $int } )? ]
type: //seq
contents:
  - type: //int
  - type: //str
tail:
  type: //arr
  size: { min: 0, max: 1 }
  contents:
    type: //rec
    contents:
      foo: { type: //int }
---
# [ $int, $str; $str, $int, $str ]
type: //seq
contents:
  - type: //int
  - type: //str
tail:
  type: //seq/cumulative
  contents:
    - type: //str
    - type: //int
    - type: //str
---
type: //seq
contents:
  - type: /codesimply.com/hostport
  - type: /codesimply.com/hostport
tail:
  type: //arr
  size: { min: 1, max: 100 }
  contents: { type: //str }
---
type: //rec
contents:
  account_id: { type: /pobox.com/account }
  sender:     { type: /pobox.com/email/env_addr }
  recipients:  
    type: //arr
    contents: 
      type: /pobox.com/email/env_addr
      size: { min: 1 }
